import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Language = 'fr' | 'en';

type Dictionary = Record<string, string>;

const dictionaries: Record<Language, Dictionary> = {
  fr: {
    'app.subtitle': 'Cockpit d’investigation offline',
    'app.version': 'ADFT v1.0',
    'lang.fr': 'FR',
    'lang.en': 'EN',
    'sidebar.integratedGui': 'GUI intégrée',
    'sidebar.overview': 'Vue d’ensemble',
    'sidebar.analysis': 'Analyse',
    'sidebar.alerts': 'Alertes',
    'sidebar.investigations': 'Investigations',
    'sidebar.timeline': 'Timeline',
    'sidebar.reconstruction': 'Reconstruction',
    'sidebar.graph': 'Graphe',
    'sidebar.benchmark': 'Benchmark',
    'sidebar.hardening': 'Hardening',
    'sidebar.exports': 'Exports',
    'analysis.title': 'Analyse',
    'analysis.subtitle': 'GUI officielle ADFT : conversion canonique JSONL puis investigation offline pilotée par le moteur.',
    'analysis.sources': 'Sources',
    'analysis.supportedFormats': 'Formats supportés : JSON, JSONL, NDJSON, EVTX, YAML, CSV, CEF, LEEF, XML, LOG, SYSLOG, TXT, Markdown, ZIP.',
    'analysis.files': 'Fichiers',
    'analysis.folder': 'Dossier',
    'analysis.clear': 'Vider',
    'analysis.refresh': 'Rafraîchir',
    'analysis.noFiles': 'Aucun fichier sélectionné',
    'analysis.unsupported': '{count} fichier(s) non supporté(s) dans la sélection.',
    'analysis.convertOnly': 'Conversion only',
    'analysis.fullAnalysis': 'Analyse complète',
    'analysis.progress': 'Progression',
    'analysis.waiting': 'En attente d’action...',
    'analysis.backendState': 'État backend',
    'analysis.release': 'Release',
    'analysis.evtx': 'EVTX',
    'analysis.evtxAvailable': 'python-evtx disponible',
    'analysis.evtxMissing': 'python-evtx absent',
    'analysis.lastRefresh': 'Dernier rafraîchissement',
    'analysis.refreshOk': 'État backend rechargé avec succès.',
    'analysis.refreshError': 'Échec du rafraîchissement',
    'analysis.never': 'Jamais',
    'analysis.outputDir': 'Répertoire de sortie',
    'analysis.lastEngineResult': 'Dernier résultat moteur',
    'analysis.sourcesCount': 'Sources',
    'analysis.alertsCount': 'Alertes',
    'analysis.investigationsCount': 'Investigations',
    'analysis.graphNodes': 'Nœuds graphe',
    'analysis.graphEdges': 'Liens graphe',
    'analysis.eventsAnalyzed': 'Événements analysés',
    'analysis.canonicalManifest': 'Manifest canonique JSONL',
    'analysis.noManifest': 'Aucun manifeste de conversion disponible pour le moment.',
    'analysis.filesScanned': 'Fichiers scannés',
    'analysis.filesConverted': 'Fichiers convertis',
    'analysis.filesFailed': 'Fichiers en échec',
    'analysis.filesSkipped': 'Fichiers ignorés',
    'analysis.eventsWritten': 'Événements écrits',
    'analysis.artifacts': 'Artefacts',
    'analysis.noArtifacts': 'Aucun artefact généré sur le run courant.',
    'analysis.generatedAt': 'généré',
    'overview.title': 'Vue d’ensemble',
    'overview.subtitle': 'Tableau de bord de l’investigation forensique',
    'overview.emptyTitle': 'Aucune analyse chargée',
    'overview.emptySubtitle': 'Importez des fichiers dans l’onglet Analyse pour démarrer',
    'overview.risk': 'Risque global',
    'overview.alerts': 'Alertes',
    'overview.investigations': 'Investigations',
    'overview.impactedAccounts': 'Comptes touchés',
    'overview.impactedHosts': 'Hôtes touchés',
    'overview.lateralPaths': 'Trajectoires latérales',
    'overview.sourceIps': 'IPs sources',
    'overview.criticalAssets': '⚠ {count} actif(s) AD critique(s) impacté(s)',
    'overview.execSummary': 'Résumé exécutif',
    'overview.execText': 'Analyse de {events} événements provenant de {sources} source(s). {alerts} alertes détectées, dont {critical} critiques. {investigations} investigation(s) ouverte(s). Niveau de risque global : {risk}.',
    'overview.topAlerts': 'Top alertes',
    'alerts.title': 'Alertes',
    'alerts.detected': '{count} alertes détectées',
    'alerts.empty': 'Aucune alerte — lancez une analyse d’abord',
    'alerts.search': 'Rechercher...',
    'alerts.id': 'ID',
    'alerts.severity': 'Sévérité',
    'alerts.rule': 'Règle',
    'alerts.mitre': 'MITRE',
    'alerts.host': 'Hôte',
    'alerts.user': 'Utilisateur',
    'alerts.ip': 'IP',
    'alerts.date': 'Date',
    'alerts.investigation': 'Investigation',
    'alerts.description': 'Description',
    'alerts.unassigned': 'Non assignée',
    'alerts.sourceEvent': 'Événement source',
    'investigations.title': 'Investigations',
    'investigations.empty': 'Aucune investigation — lancez une analyse d’abord',
    'investigations.score': 'Score',
    'investigations.linkedAlerts': 'Alertes liées',
    'investigations.hypothesis': 'Hypothèse',
    'investigations.analystSummary': 'Résumé analyste',
    'investigations.managerSummary': 'Résumé manager',
    'investigations.entities': 'Entités impliquées',
    'investigations.select': 'Sélectionnez une investigation',
    'timeline.title': 'Timeline',
    'timeline.empty': 'Aucune timeline — lancez une analyse d’abord',
    'timeline.filter': 'Filtrer par entité, texte...',
    'timeline.event': 'événement',
    'timeline.alert': 'alerte',
    'timeline.investigation': 'investigation',
    'reconstruction.title': 'Reconstruction',
    'reconstruction.empty': 'Aucune reconstruction — lancez une analyse d’abord',
    'reconstruction.attackTitle': 'Reconstruction d’attaque',
    'reconstruction.chain': 'Attack Chain (Kill Chain)',
    'reconstruction.step': 'Étape {step}',
    'reconstruction.patientZero': 'Patient Zero',
    'reconstruction.confidence': 'Confiance',
    'reconstruction.attackPath': 'Attack Path',
    'reconstruction.impacts': 'Impacts estimés',
    'reconstruction.story': 'Récit de l’attaque',
    'graph.title': 'Graphe d’entités',
    'graph.subtitle': 'Pivot centré, relations orientées, fenêtre temporelle et réduction du bruit pour l’analyste.',
    'graph.empty': 'Aucun graphe d’entités — lancez une analyse d’abord',
    'graph.search': 'Rechercher...',
    'graph.start': 'Début incident',
    'graph.end': 'Fin incident',
    'graph.fullWindow': 'Fenêtre complète',
    'graph.pivot': 'Pivot',
    'graph.nodesShown': 'Nœuds affichés',
    'graph.visibleLinks': 'Liens visibles',
    'graph.zoom': 'Zoom',
    'graph.zoomIn': 'Zoomer',
    'graph.zoomOut': 'Dézoomer',
    'graph.resetZoom': 'Réinitialiser le zoom',
    'graph.fullscreen': 'Plein écran',
    'graph.exitFullscreen': 'Quitter le plein écran',
    'graph.help': 'Glisser le fond pour naviguer, molette pour zoomer, glisser un nœud pour le déplacer.',
    'graph.iocKnown': 'IOC connu = anneau pointillé rouge',
    'graph.maxNodes': 'Max 50 nœuds affichés par page',
    'graph.hidden': '{count} nœud(s) masqué(s) par filtres ou pagination.',
    'graph.prev': 'Préc.',
    'graph.next': 'Suiv.',
    'graph.page': 'Page {page} / {total}',
    'graph.selectedNode': 'Nœud sélectionné',
    'graph.selectPrompt': 'Sélectionnez un nœud pour voir son contexte, son score, ses timestamps et ses relations.',
    'graph.risk': 'Risque',
    'graph.alerts': 'Alertes',
    'graph.degree': 'Degré',
    'graph.firstSeen': 'First seen',
    'graph.lastSeen': 'Last seen',
    'graph.criticalEntity': 'Entité critique',
    'graph.standardCriticality': 'Criticité standard',
    'graph.noKnownIoc': 'Pas d’IOC connu',
    'graph.graphOccurrences': 'Occurrences graphe : {count}',
    'graph.centerNode': 'Centrer sur ce nœud',
    'graph.expand': 'Étendre d’un niveau',
    'graph.collapse': 'Réduire d’un niveau',
    'graph.visibleRelations': 'Relations visibles',
    'graph.noRelations': 'Aucune relation dans la fenêtre temporelle active.',
    'graph.weight': 'poids',
    'benchmark.title': 'Benchmark',
    'benchmark.subtitle': 'Vue de validation produit : état runtime, performances réelles du moteur, installation EVTX et surface packagée pour la release GitHub.',
    'benchmark.release': 'Release',
    'benchmark.conversion': 'Conversion',
    'benchmark.convertedFiles': 'fichier(s) converti(s)',
    'benchmark.pipeline': 'Pipeline',
    'benchmark.eventsAnalyzed': 'événement(s) analysé(s)',
    'benchmark.evtxDependency': 'dépendance optionnelle python-evtx',
    'benchmark.releaseCheck': 'Check release',
    'benchmark.toHandle': 'À traiter',
    'benchmark.runMetrics': 'Métriques de run',
    'benchmark.packagedSurface': 'Surface packagée',
    'benchmark.guiMode': 'GUI mode',
    'benchmark.outputDir': 'Output dir',
    'benchmark.lastRun': 'Dernier run',
    'benchmark.lastRefresh': 'Dernier refresh',
    'benchmark.noRun': 'Aucun',
    'benchmark.patientZero': 'Patient zero',
    'benchmark.availableArtifacts': 'Artefacts présents',
    'benchmark.noArtifacts': 'Aucun artefact disponible.',
    'benchmark.systemStats': 'Stats runtime observées',
    'benchmark.systemStatsHint': 'Métriques réelles issues du moteur ADFT et du jeu chargé, sans métriques système inventées.',
    'benchmark.observedRate': 'Débit moteur',
    'benchmark.alertDensity': 'Densité d’alertes',
    'benchmark.peakBucket': 'Pic de fenêtre',
    'benchmark.graphDensity': 'Densité du graphe',
    'benchmark.artifactFootprint': 'Poids des artefacts',
    'benchmark.sourceCount': 'Sources chargées',
    'benchmark.runtime': 'Runtime',
    'benchmark.incidentTempo': 'Tempo incident',
    'benchmark.activityCurve': 'Courbe d’activité',
    'benchmark.activityCurveHint': 'Volume d’événements observés par fenêtre temporelle sur l’incident chargé.',
    'benchmark.pipelineShape': 'Surface pipeline',
    'benchmark.pipelineShapeHint': 'Comparaison visuelle des volumes produits par le moteur ADFT.',
    'benchmark.observationWindow': 'Fenêtre observée',
    'benchmark.series.events': 'Événements',
    'benchmark.series.alerts': 'Alertes',
    'benchmark.series.investigations': 'Investigations',
    'benchmark.series.timeline': 'Timeline',
    'benchmark.series.nodes': 'Nœuds',
    'benchmark.series.edges': 'Arêtes',
    'benchmark.recommendation': 'Validation benchmark',
    'benchmark.recommendationText': 'Cette page sert de point de contrôle avant publication GitHub : vérifier que l’UI lit l’état réel du backend, que le débit moteur reste cohérent, que les artefacts sont présents, que la dépendance EVTX est installée et que le run de démonstration produit un graphe, une timeline, des alertes et des exports cohérents.',
    'hardening.title': 'Hardening',
    'hardening.empty': 'Aucune recommandation — lancez une analyse d’abord',
    'hardening.subtitle': '{count} recommandations issues des preuves observées.',
    'hardening.exportScripts': 'Exporter les scripts',
    'hardening.expectedImpact': 'Impact attendu',
    'hardening.sourceEvidence': 'Preuves sources',
    'exports.title': 'Exports',
    'exports.subtitle': 'Artefacts réels générés par le moteur ADFT pour le run courant.',
    'exports.empty': 'Aucune donnée à exporter — lancez une analyse d’abord',
    'exports.preview': 'Prévisualiser',
    'exports.download': 'Télécharger',
    'notfound.message': 'Oups, page introuvable',
    'notfound.back': 'Retour à l’accueil',
    'common.na': 'N/A',
    'common.none': 'Aucun',
    'common.role': 'rôle',
    'common.ok': 'OK',
    'common.refresh': 'Rafraîchir',
    'difficulty.easy': '🟢 Facile',
    'difficulty.medium': '🟡 Moyen',
    'difficulty.hard': '🔴 Difficile',
    'entity.user': 'Utilisateur',
    'entity.host': 'Hôte',
    'entity.ip': 'IP',
    'entity.process': 'Processus',
    'entity.service': 'Service',
    'entity.ad_object': 'Objet AD',
    'severity.critical': 'critique',
    'severity.high': 'élevé',
    'severity.medium': 'moyen',
    'severity.low': 'faible',
    'severity.info': 'info',
    'status.initializingAnalysis': 'Préparation de l’analyse',
    'status.initializingConversion': 'Préparation de la conversion',
    'stage.initialization': 'Initialisation',
    'stage.conversion': 'Conversion JSONL',
    'stage.ingestion': 'Ingestion',
    'stage.normalization': 'Normalisation',
    'stage.detection': 'Détection',
    'stage.correlation': 'Corrélation',
    'stage.timeline': 'Timeline',
    'stage.entity_graph': 'Graphe',
    'stage.risk_scoring': 'Scoring',
    'stage.hardening': 'Hardening',
    'stage.reporting': 'Reporting',
    'stage.exports': 'Exports',
  },
  en: {
    'app.subtitle': 'Offline investigation cockpit',
    'app.version': 'ADFT v1.0',
    'lang.fr': 'FR',
    'lang.en': 'EN',
    'sidebar.integratedGui': 'Integrated GUI',
    'sidebar.overview': 'Overview',
    'sidebar.analysis': 'Analysis',
    'sidebar.alerts': 'Alerts',
    'sidebar.investigations': 'Investigations',
    'sidebar.timeline': 'Timeline',
    'sidebar.reconstruction': 'Reconstruction',
    'sidebar.graph': 'Graph',
    'sidebar.benchmark': 'Benchmark',
    'sidebar.hardening': 'Hardening',
    'sidebar.exports': 'Exports',
    'analysis.title': 'Analysis',
    'analysis.subtitle': 'Official ADFT GUI: canonical JSONL conversion followed by offline investigation driven by the engine.',
    'analysis.sources': 'Sources',
    'analysis.supportedFormats': 'Supported formats: JSON, JSONL, NDJSON, EVTX, YAML, CSV, CEF, LEEF, XML, LOG, SYSLOG, TXT, Markdown, ZIP.',
    'analysis.files': 'Files',
    'analysis.folder': 'Folder',
    'analysis.clear': 'Clear',
    'analysis.refresh': 'Refresh',
    'analysis.noFiles': 'No file selected',
    'analysis.unsupported': '{count} unsupported file(s) in selection.',
    'analysis.convertOnly': 'Convert only',
    'analysis.fullAnalysis': 'Full analysis',
    'analysis.progress': 'Progress',
    'analysis.waiting': 'Waiting for action...',
    'analysis.backendState': 'Backend state',
    'analysis.release': 'Release',
    'analysis.evtx': 'EVTX',
    'analysis.evtxAvailable': 'python-evtx available',
    'analysis.evtxMissing': 'python-evtx missing',
    'analysis.lastRefresh': 'Last refresh',
    'analysis.refreshOk': 'Backend state reloaded successfully.',
    'analysis.refreshError': 'Refresh failed',
    'analysis.never': 'Never',
    'analysis.outputDir': 'Output directory',
    'analysis.lastEngineResult': 'Latest engine result',
    'analysis.sourcesCount': 'Sources',
    'analysis.alertsCount': 'Alerts',
    'analysis.investigationsCount': 'Investigations',
    'analysis.graphNodes': 'Graph nodes',
    'analysis.graphEdges': 'Graph edges',
    'analysis.eventsAnalyzed': 'Analyzed events',
    'analysis.canonicalManifest': 'Canonical JSONL manifest',
    'analysis.noManifest': 'No conversion manifest available yet.',
    'analysis.filesScanned': 'Files scanned',
    'analysis.filesConverted': 'Files converted',
    'analysis.filesFailed': 'Files failed',
    'analysis.filesSkipped': 'Files skipped',
    'analysis.eventsWritten': 'Events written',
    'analysis.artifacts': 'Artifacts',
    'analysis.noArtifacts': 'No artifact generated for the current run.',
    'analysis.generatedAt': 'generated',
    'overview.title': 'Overview',
    'overview.subtitle': 'Forensic investigation dashboard',
    'overview.emptyTitle': 'No analysis loaded',
    'overview.emptySubtitle': 'Import files in the Analysis tab to get started',
    'overview.risk': 'Global risk',
    'overview.alerts': 'Alerts',
    'overview.investigations': 'Investigations',
    'overview.impactedAccounts': 'Impacted accounts',
    'overview.impactedHosts': 'Impacted hosts',
    'overview.lateralPaths': 'Lateral paths',
    'overview.sourceIps': 'Source IPs',
    'overview.criticalAssets': '⚠ {count} impacted critical AD asset(s)',
    'overview.execSummary': 'Executive summary',
    'overview.execText': 'Analysis of {events} events from {sources} source(s). {alerts} alerts detected, including {critical} critical. {investigations} investigation(s) opened. Overall risk level: {risk}.',
    'overview.topAlerts': 'Top alerts',
    'alerts.title': 'Alerts',
    'alerts.detected': '{count} detected alert(s)',
    'alerts.empty': 'No alerts — run an analysis first',
    'alerts.search': 'Search...',
    'alerts.id': 'ID',
    'alerts.severity': 'Severity',
    'alerts.rule': 'Rule',
    'alerts.mitre': 'MITRE',
    'alerts.host': 'Host',
    'alerts.user': 'User',
    'alerts.ip': 'IP',
    'alerts.date': 'Date',
    'alerts.investigation': 'Investigation',
    'alerts.description': 'Description',
    'alerts.unassigned': 'Unassigned',
    'alerts.sourceEvent': 'Source event',
    'investigations.title': 'Investigations',
    'investigations.empty': 'No investigation — run an analysis first',
    'investigations.score': 'Score',
    'investigations.linkedAlerts': 'Linked alerts',
    'investigations.hypothesis': 'Hypothesis',
    'investigations.analystSummary': 'Analyst summary',
    'investigations.managerSummary': 'Manager summary',
    'investigations.entities': 'Involved entities',
    'investigations.select': 'Select an investigation',
    'timeline.title': 'Timeline',
    'timeline.empty': 'No timeline — run an analysis first',
    'timeline.filter': 'Filter by entity, text...',
    'timeline.event': 'event',
    'timeline.alert': 'alert',
    'timeline.investigation': 'investigation',
    'reconstruction.title': 'Reconstruction',
    'reconstruction.empty': 'No reconstruction — run an analysis first',
    'reconstruction.attackTitle': 'Attack reconstruction',
    'reconstruction.chain': 'Attack Chain (Kill Chain)',
    'reconstruction.step': 'Step {step}',
    'reconstruction.patientZero': 'Patient zero',
    'reconstruction.confidence': 'Confidence',
    'reconstruction.attackPath': 'Attack path',
    'reconstruction.impacts': 'Estimated impacts',
    'reconstruction.story': 'Attack narrative',
    'graph.title': 'Entity graph',
    'graph.subtitle': 'Centered pivot, directed relations, incident time window and noise reduction for the analyst.',
    'graph.empty': 'No entity graph — run an analysis first',
    'graph.search': 'Search...',
    'graph.start': 'Incident start',
    'graph.end': 'Incident end',
    'graph.fullWindow': 'Full window',
    'graph.pivot': 'Pivot',
    'graph.nodesShown': 'Displayed nodes',
    'graph.visibleLinks': 'Visible links',
    'graph.zoom': 'Zoom',
    'graph.help': 'Drag the background to navigate, use the wheel to zoom, drag a node to move it.',
    'graph.iocKnown': 'Known IOC = red dashed ring',
    'graph.maxNodes': 'Max 50 nodes displayed per page',
    'graph.hidden': '{count} node(s) hidden by filters or pagination.',
    'graph.prev': 'Prev.',
    'graph.next': 'Next',
    'graph.page': 'Page {page} / {total}',
    'graph.selectedNode': 'Selected node',
    'graph.selectPrompt': 'Select a node to inspect context, score, timestamps and relationships.',
    'graph.risk': 'Risk',
    'graph.alerts': 'Alerts',
    'graph.degree': 'Degree',
    'graph.firstSeen': 'First seen',
    'graph.lastSeen': 'Last seen',
    'graph.criticalEntity': 'Critical entity',
    'graph.standardCriticality': 'Standard criticality',
    'graph.noKnownIoc': 'No known IOC',
    'graph.graphOccurrences': 'Graph occurrences: {count}',
    'graph.centerNode': 'Center on this node',
    'graph.expand': 'Expand by one hop',
    'graph.collapse': 'Collapse by one hop',
    'graph.visibleRelations': 'Visible relationships',
    'graph.noRelations': 'No relationship in the active time window.',
    'graph.weight': 'weight',
    'benchmark.title': 'Benchmark',
    'benchmark.subtitle': 'Product validation view: runtime state, real engine performance, EVTX install status and packaged surface for the GitHub release.',
    'benchmark.release': 'Release',
    'benchmark.conversion': 'Conversion',
    'benchmark.convertedFiles': 'converted file(s)',
    'benchmark.pipeline': 'Pipeline',
    'benchmark.eventsAnalyzed': 'analyzed event(s)',
    'benchmark.evtxDependency': 'optional python-evtx dependency',
    'benchmark.releaseCheck': 'Release checks',
    'benchmark.toHandle': 'Needs work',
    'benchmark.runMetrics': 'Run metrics',
    'benchmark.packagedSurface': 'Packaged surface',
    'benchmark.guiMode': 'GUI mode',
    'benchmark.outputDir': 'Output dir',
    'benchmark.lastRun': 'Last run',
    'benchmark.lastRefresh': 'Last refresh',
    'benchmark.noRun': 'None',
    'benchmark.patientZero': 'Patient zero',
    'benchmark.availableArtifacts': 'Available artifacts',
    'benchmark.noArtifacts': 'No artifact available.',
    'benchmark.systemStats': 'Observed runtime stats',
    'benchmark.systemStatsHint': 'Real metrics computed from the ADFT engine and the loaded dataset, without fake host telemetry.',
    'benchmark.observedRate': 'Engine throughput',
    'benchmark.alertDensity': 'Alert density',
    'benchmark.peakBucket': 'Peak window',
    'benchmark.graphDensity': 'Graph density',
    'benchmark.artifactFootprint': 'Artifact footprint',
    'benchmark.sourceCount': 'Loaded sources',
    'benchmark.runtime': 'Runtime',
    'benchmark.incidentTempo': 'Incident tempo',
    'benchmark.activityCurve': 'Activity curve',
    'benchmark.activityCurveHint': 'Observed event volume per time bucket for the loaded incident.',
    'benchmark.pipelineShape': 'Pipeline shape',
    'benchmark.pipelineShapeHint': 'Visual comparison of the volumes produced by the ADFT engine.',
    'benchmark.observationWindow': 'Observed window',
    'benchmark.series.events': 'Events',
    'benchmark.series.alerts': 'Alerts',
    'benchmark.series.investigations': 'Investigations',
    'benchmark.series.timeline': 'Timeline',
    'benchmark.series.nodes': 'Nodes',
    'benchmark.series.edges': 'Edges',
    'benchmark.recommendation': 'Benchmark validation',
    'benchmark.recommendationText': 'Use this page as a control point before publishing to GitHub: verify that the UI reads the real backend state, that engine throughput remains coherent, that artifacts are present, that EVTX is installed, and that the demo run produces a coherent graph, timeline, alerts and exports.',
    'hardening.title': 'Hardening',
    'hardening.empty': 'No recommendation — run an analysis first',
    'hardening.subtitle': '{count} recommendation(s) derived from observed evidence.',
    'hardening.exportScripts': 'Export scripts',
    'hardening.expectedImpact': 'Expected impact',
    'hardening.sourceEvidence': 'Source evidence',
    'exports.title': 'Exports',
    'exports.subtitle': 'Real artifacts generated by the ADFT engine for the current run.',
    'exports.empty': 'No data to export — run an analysis first',
    'exports.preview': 'Preview',
    'exports.download': 'Download',
    'notfound.message': 'Oops! Page not found',
    'notfound.back': 'Return home',
    'common.na': 'N/A',
    'common.none': 'None',
    'common.role': 'role',
    'common.ok': 'OK',
    'common.refresh': 'Refresh',
    'difficulty.easy': '🟢 Easy',
    'difficulty.medium': '🟡 Medium',
    'difficulty.hard': '🔴 Hard',
    'entity.user': 'User',
    'entity.host': 'Host',
    'entity.ip': 'IP',
    'entity.process': 'Process',
    'entity.service': 'Service',
    'entity.ad_object': 'AD object',
    'severity.critical': 'critical',
    'severity.high': 'high',
    'severity.medium': 'medium',
    'severity.low': 'low',
    'severity.info': 'info',
    'status.initializingAnalysis': 'Preparing analysis',
    'status.initializingConversion': 'Preparing conversion',
    'stage.initialization': 'Initialization',
    'stage.conversion': 'JSONL conversion',
    'stage.ingestion': 'Ingestion',
    'stage.normalization': 'Normalization',
    'stage.detection': 'Detection',
    'stage.correlation': 'Correlation',
    'stage.timeline': 'Timeline',
    'stage.entity_graph': 'Graph',
    'stage.risk_scoring': 'Scoring',
    'stage.hardening': 'Hardening',
    'stage.reporting': 'Reporting',
    'stage.exports': 'Exports',
  },
};

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const STORAGE_KEY = 'adft-ui-language';
const LanguageContext = createContext<LanguageContextValue | null>(null);

function interpolate(template: string, vars?: Record<string, string | number>) {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_, key) => String(vars[key] ?? `{${key}}`));
}

function detectDefaultLanguage(): Language {
  if (typeof window === 'undefined') return 'fr';
  const stored = window.localStorage.getItem(STORAGE_KEY);
  if (stored === 'fr' || stored === 'en') return stored;
  return window.navigator.language.toLowerCase().startsWith('fr') ? 'fr' : 'en';
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(detectDefaultLanguage);

  useEffect(() => {
    if (typeof window === 'undefined') return;
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (next: Language) => setLanguageState(next);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    t: (key, vars) => interpolate(dictionaries[language][key] || dictionaries.fr[key] || key, vars),
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}

export function translateForLanguage(language: Language, key: string, vars?: Record<string, string | number>) {
  return interpolate(dictionaries[language][key] || dictionaries.fr[key] || key, vars);
}

export function severityLabel(language: Language, severity: string) {
  return translateForLanguage(language, `severity.${severity}`);
}

export function entityTypeLabel(language: Language, type: string) {
  return translateForLanguage(language, `entity.${type}`);
}

export function difficultyLabel(language: Language, difficulty: string) {
  return translateForLanguage(language, `difficulty.${difficulty}`);
}
